### ISSUE TITLE
JSON output is truncated in GH action at liberator repo

### ISSUE THREAD

**Issue by borkdude** [DeLaGuardo/clojure-lint-action#1]
See https://github.com/clojure-liberator/liberator/runs/292756294

**Comment by DeLaGuardo** [comment]
Just pushed the fix. Could you please try `DeLaGuardo/clojure-lint-action@master` version?

**Comment by borkdude** [comment]
@ordnungswidrig ^

**Comment by borkdude** [comment]
@DeLaGuardo I don't think concatenating stderr with stdout results in valid JSON.

For reference, here's how @marcomorain's clojure-lint extension handles it:

https://github.com/marcomorain/clojure-lint/blob/30a4b369d7fdce2d00a26810c7649d995714e2d3/src/extension.ts#L55

**Comment by DeLaGuardo** [comment]
I keep stderr and stdout separated. The only stdout is going to json parser. stderr is only for action logging.

**Comment by ordnungswidrig** [comment]
@DeLaGuardo unfortunately now failed with a different error. I might be doing something wrong, though. 

https://github.com/clojure-liberator/liberator/commit/4de95d28b259f12f130bdccfae5d3ad7f8447cd9/checks?check_suite_id=301764751

**Comment by DeLaGuardo** [comment]
Sorry, that was my fault. Could you try again?

**Comment by DeLaGuardo** [comment]
I can confirm that action is working with the latest master branch - https://github.com/DeLaGuardo/liberator/runs/294260904

**Comment by DeLaGuardo** [comment]
Also, link to the page with linting problems was added to the action report

**Comment by ordnungswidrig** [comment]
Thanks it's working now!
